version: '3.7'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_PASSWORD: pode12345
      MYSQL_USER: maan
      MYSQL_DATABASE: maan
    network_mode: "bridge"
